version: "3.10"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "gunicorn fileupload.wsgi:application --bind 0.0.0.0:8000 --workers=2"
    #command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: fileupload
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306